# Site settings
title: Kyle Nazario's published stories
email: kylebnazario@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Everything I've had published at previous positions. Feel free to 
  browse my published works and see my progression as a writer, and 
  don't judge the early stuff too harshly. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kylenazario.com" # the base hostname & protocol for your site
twitter_username: kbn_le
github_username:  kyle-n

# Build settings
markdown: kramdown
