# Site settings
title: Kyle Nazario
description: Frontend web developer creating awesome projects for the web and mobile.
url: https://www.kylenazario.com
baseurl: ""

# User settings
username: Kyle Nazario
user_description:
  Talented engineer helping teams ship great software. Frontend consultant for
  <a href="https://www.bitovi.com/" target="_blank">Bitovi</a> by day, making
  <a href="https://www.nazariosoftware.com" target="_blank">cool side projects</a> by night.
user_title: Software Engineer
email: kylebnazario@gmail.com
linkedin_username: kylenazario
twitter_username: kbn_au
github_username: kyle-n
mastodon_profile: https://hachyderm.io/@kn
rss_url: /atom.xml
google_analytics: G-KZY3WL4S3X

exclude: ["package.json", "src", "node_modules", "vendor"]

# Hyde theme
highlighter: pygments

# Permalinks
permalink: pretty
author:
  name: "Kyle Nazario"
  url: https://twitter.com/kbn_au
paginate: 5

plugins:
  - jekyll-redirect-from
